export enum ErrorCode {
  // General
  INTERNAL_SERVER_ERROR = "ERR-5000",
  UNKNOWN_ERROR = "ERR-5001",

  // Validation
  INVALID_REQUEST = "ERR-4000",
  MISSING_REQUIRED_FIELD = "ERR-4001",
  INVALID_TRANSACTION = "ERR-4002",

  // Authentication
  UNAUTHORIZED = "ERR-4010",
  FORBIDDEN = "ERR-4030",

  // Connectors
  PAYMENT_CONNECTOR_FAILED = "ERR-5100",
  LEDGER_CONNECTOR_FAILED = "ERR-5101",
  DATABASE_CONNECTION_FAILED = "ERR-5102",

  // Reconciliation
  MATCHING_FAILED = "ERR-5200",
  REPORT_GENERATION_FAILED = "ERR-5201",
  DISCREPANCY_CLASSIFICATION_FAILED = "ERR-5202",

  // External Services
  PAYSTACK_API_ERROR = "ERR-5300",
  MONO_API_ERROR = "ERR-5301",
  FLUTTERWAVE_API_ERROR = "ERR-5302"
}