export const APP_NAME = "Sync45";

export const RECONCILIATION_STATUS = {
  PENDING: "PENDING",
  RUNNING: "RUNNING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED",
} as const;

export const DISCREPANCY_TYPE = {
  MISSING: "MISSING",
  DUPLICATE: "DUPLICATE",
  MISMATCH: "MISMATCH",
  UNMATCHED: "UNMATCHED",
} as const;

export const EVENT_NAME = {
  RECONCILIATION_STARTED: "RECONCILIATION_STARTED",
  RECONCILIATION_COMPLETED: "RECONCILIATION_COMPLETED",
  REPORT_GENERATED: "REPORT_GENERATED",
} as const;

export const CONNECTOR_NAME = {
  PAYSTACK: "PAYSTACK",
  MONGODB: "MONGODB",
} as const;