export enum ReconciliationEvent {
  RECONCILIATION_STARTED = "RECONCILIATION_STARTED",

  PAYMENT_TRANSACTIONS_FETCHED = "PAYMENT_TRANSACTIONS_FETCHED",

  LEDGER_TRANSACTIONS_FETCHED = "LEDGER_TRANSACTIONS_FETCHED",

  TRANSACTIONS_NORMALIZED = "TRANSACTIONS_NORMALIZED",

  TRANSACTIONS_MATCHED = "TRANSACTIONS_MATCHED",

  DISCREPANCIES_DETECTED = "DISCREPANCIES_DETECTED",

  REPORT_GENERATED = "REPORT_GENERATED",

  RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED",

  RECONCILIATION_FAILED = "RECONCILIATION_FAILED"
}

export interface ReconciliationEventPayload {
  organizationId: string;

  reconciliationId: string;

  timestamp: Date;

  metadata?: Record<string, any>;
}